config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/policy'
  get :sitemap, to: redirect('static_pages/sitemap.%{format}', status: 301)
  root 'genres#index'
  resources :genres, :only => ["index", "show"] do
    resources :books, :only => ["show"]
  end
  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :books
  validates :strId, presence: true, uniqueness: true

  def delete_old
    self.books.each{|item|
      item.delete if (Date.today - item.salesDate) > ELAPSED_DAYS
    }
  end

  def self.get_summary
    url = RAKUTEN_GENRE_URI + '20131010'
    params = {:format => 'json', :koboGenreId => 101, :applicationId => KOBOAPI_APPLICATION_ID}
    unless params[:applicationId]
      return
    else
      results = exec_api(url, params)
    end
    results["children"].each_with_index{|item, i|
      Genre.create(
        :strId => item["child"]["koboGenreId"],
        :name => item["child"]["koboGenreName"],
        :level => item["child"]["genreLevel"]
      )
    }
  end

  def get_books_summary
    url = RAKUTEN_KWL_URI + '20140811'
    params = {:format => 'json', :koboGenreId => self.strId, :sort => '-releaseDate', :salesType => 0, :applicationId => KOBOAPI_APPLICATION_ID}
    unless params[:applicationId]
      return
    else
      results = Genre.exec_api(url, params)
    end
    results["Items"].each_with_index{|item, i|
      self.books.create(
        :title => item["Item"]["title"],
        :titleKana => item["Item"]["titleKana"],
        :subTitle => item["Item"]["subTitle"],
        :seriesName => item["Item"]["seriesName"],
        :author => item["Item"]["author"],
        :authorKana => item["Item"]["authorKana"],
        :publisherName => item["Item"]["publisherName"],
        :language => item["Item"]["language"],
        :salesDate => Date.strptime(item["Item"]["salesDate"], "%Y年%m月%d日"),
        :itemNumber => item["Item"]["itemNumber"],
        :koboGenreId => item["Item"]["koboGenreId"],
        :itemCaption => item["Item"]["itemCaption"],
        :itemPrice => item["Item"]["itemPrice"],
        :itemUrl => item["Item"]["itemUrl"],
        :affiliateUrl => item["Item"]["affiliateUrl"],
        :smallImageUrl => item["Item"]["smallImageUrl"],
        :mediumImageUrl => item["Item"]["mediumImageUrl"],
        :largeImageUrl => item["Item"]["largeImageUrl"],
        :reviewCount => item["Item"]["reviewCount"],
        :reviewAverage => item["Item"]["reviewAverage"],
        :salesType => item["Item"]["salesType"]
      )
    }
  end

  private
  def self.exec_api(url, params)
    params = params.to_a.map() do |item|
      [item.first.to_s, CGI.escape(item.last.to_s)]
    end.sort
    param_string = params.map() {|key, value| "#{key}=#{value}"}.join('&')
    base_string = ['GET', CGI.escape(url), CGI.escape(param_string)].join('&')
    uri_string = url + '?' + param_string

    Net::HTTP.version_1_2
    uri = URI.parse(uri_string)
    json = Net::HTTP.get(uri)
    results = JSON.parse(json)

  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
p "Genres.index"
    Genre.get_summary
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
p "Genres.show"
    @genre = Genre.find(params[:id])
    @genre.delete_old
    @genre.get_books_summary
    # @books = @genre.books.order(salesDate: :desc, publisherName: :asc, author: :asc).limit(RECORD_LIMIT)
    @books = @genre.books.order(salesDate: :desc, publisherName: :asc, author: :asc).paginate(page: params[:page])
#    render json: @books.to_json
    render
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:strId, :name, :level)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :strId %><br>
    <%= f.text_field :strId %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container" id="chkDisplay" style="border: 1px; border-style: solid; border-color: #f0f0f0;">
  画像のみ <%= radio_button_tag 'dispflag', 'image', true %>｜
  テキストのみ<%= radio_button_tag 'dispflag', 'text' %>｜
  画像＋テキスト<%= radio_button_tag 'dispflag', 'imgtext' %>  
</div>
<div class="container" id="board">
  <ul class="list-unstyled">
    <% @genres.each do |genre| %>
    <li><%= link_to(genre.name, genre, class: "btn btn-info", id: "parent" + genre.strId, remote: true) %>
      <%= button_tag("閉じる", class: "cancel", value: genre.strId, id: "btn" + genre.strId, type: :button, style: "display: none;") %>
      <ul class="list-inline" id="<%=genre.strId %>"></ul>
    </li>
    <% end %>
  </ul>
<p>※予約販売は検索対象外</p>
</div>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form' %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to(@genre.name, genres_path, class: "btn btn-info") %>
<div class="contaner">
  <% if @genre.books.any? %>
    <ul class="list-inline">
      <%= render @books %>
    </ul>
    <%= will_paginate @books, previous_label: "前ページ", next_label: "次ページ" %>
  <% end %>
</div>
<p>※予約販売は検索対象外</p>

app/views/genres/show.js.erb
if ($('input[name=dispflag]:checked').val()==="image") {
  $("#<%= @genre.strId %>").html("<%= j(render(partial: 'books/booksimage', collection: @books)) %>");
} else if ($('input[name=dispflag]:checked').val()==="text") {
  $("#<%= @genre.strId %>").html("<%= j(render(partial: 'books/bookstext', collection: @books)) %>");
} else {
  $("#<%= @genre.strId %>").html("<%= j(render(partial: 'books/booksimgtext', collection: @books)) %>");
}
$("#btn<%= @genre.strId %>").show();
$("#<%= @genre.strId %>").show();
$("#parent<%= @genre.strId %>").text("<%= @genre.name + '（' + @genre.books.maximum('salesDate').to_s + '）' %>");